device: cuda
dataset:
  name: ImageNet
  dataset_dir: .\datasets\ImageNet_sf2
  image_size: 256
  n_channels: 3
  n_classes: 12
model:
  type: imagenet
  name: resnet
  init_mode: kaiming_fan_out
  resnet:
    initial_channels: 64
    block_type: basic
    n_blocks: [3, 4, 6, 3]
train:
  resume: False
  seed: 0
  precision: O0
  batch_size: 32
  subdivision: 1
  optimizer: sgd
  base_lr: 0.003
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: experiments/imagenet/resnet34/sf2
  log_period: 10
  checkpoint_period: 50
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 2
    drop_last: True
    pin_memory: True
validation:
  batch_size: 1
  dataloader:
    num_workers: 2
    drop_last: False
    pin_memory: True
scheduler:
  epochs: 50
  type: multistep
  milestones: [30, 60]
  lr_decay: 0.1
augmentation:
  use_random_crop: False
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
tta:
  use_resize: True
  use_center_crop: True
  resize: 256
tensorboard:
  train_images: False
  val_images: False
  model_params: False
